In [114]:
from google.colab import files
uploaded = files.upload()

Saving customer_shopping_behavior.csv to customer_shopping_behavior (2).csv

In [115]:
import pandas as pd
df = pd.read_csv('customer_shopping_behavior.csv')

In [116]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [117]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [118]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [119]:
df.describe(include="all")

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [120]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [121]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x:x.fillna(x.median()))

In [122]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [123]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ', '_')

In [124]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [125]:
df = df.rename(columns={'purchase_amount_(usd)': 'purchase_amount'})

In [126]:
labels = ['Young Adults','Adult','Middle Aged','Senior']                                                  #Creating a new column to categorize the age of the customers
df['age_group']=pd.cut(df['age'],bins=4,labels=labels)

In [127]:
df[['age','age_group']].head(10)

   age     age_group
0   55   Middle Aged
1   19  Young Adults
2   50   Middle Aged
3   21  Young Adults
4   45   Middle Aged
5   46   Middle Aged
6   63        Senior
7   27  Young Adults
8   26  Young Adults
9   57   Middle Aged

In [128]:
df.frequency_of_purchases.value_counts()

frequency_of_purchases
Every 3 Months    584
Annually          572
Quarterly         563
Monthly           553
Bi-Weekly         547
Fortnightly       542
Weekly            539
Name: count, dtype: int64

In [129]:
frequency_mapping = {
'Every 3 Months':90,
'Annually':365,
'Quarterly':90,
'Monthly':30,
'Bi-Weekly':14,
'Fortnightly':14,
'Weekly':7
}

In [130]:
df['purchase_frequency_days']=df['frequency_of_purchases'].map(frequency_mapping)            #fequency_of_purchase is in wordings which is difficult for analyze so it will be converted into numbers

In [131]:
df[['purchase_frequency_days','frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                       14            Fortnightly
1                       14            Fortnightly
2                        7                 Weekly
3                        7                 Weekly
4                      365               Annually
5                        7                 Weekly
6                       90              Quarterly
7                        7                 Weekly
8                      365               Annually
9                       90              Quarterly

In [132]:
((df['discount_applied'] == df['promo_code_used'])).all()              #Both columns are same if promo code is applied then there must have been a discount given

np.True_

In [133]:
df = df.drop(['promo_code_used'],axis=1)                                                              #so lets drop one column

In [134]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='object')

In [135]:
pip install sql

Requirement already satisfied: sql in /usr/local/lib/python3.12/dist-packages (2022.4.0)

In [136]:
import sqlite3
conn = sqlite3.connect("mydatabase.db")   # create SQL database
cursor = conn.cursor()

In [137]:
df.to_sql("mytable", conn, if_exists="replace", index=False)

3900

In [138]:
query = "SELECT * FROM mytable"
result = pd.read_sql_query(query, conn)
result

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,Middle Aged,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,Young Adults,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,Middle Aged,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,Young Adults,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,Middle Aged,365
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,No,2-Day Shipping,No,32,Venmo,Weekly,Adult,7
3896,3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,No,Store Pickup,No,41,Bank Transfer,Bi-Weekly,Middle Aged,14
3897,3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,No,Standard,No,24,Venmo,Quarterly,Middle Aged,90
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,No,Express,No,24,Venmo,Weekly,Adult,7
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,No,Store Pickup,No,33,Venmo,Quarterly,Middle Aged,90

In [139]:
query = """
SELECT
    gender,
    SUM(purchase_amount) AS total_revenue
FROM mytable
GROUP BY gender;
"""
result = pd.read_sql_query(query, conn)
result

   gender  total_revenue
0  Female          75191
1    Male         157890

In [140]:
query = """
SELECT customer_id, purchase_amount
FROM mytable
WHERE discount_applied = 'Yes'
AND purchase_amount > (
    SELECT AVG(purchase_amount) FROM mytable
);
"""
result = pd.read_sql_query(query, conn)
result

     customer_id  purchase_amount
0              2               64
1              3               73
2              4               90
3              7               85
4              9               97
..           ...              ...
834         1667               64
835         1671               73
836         1673               73
837         1674               62
838         1676               90

[839 rows x 2 columns]

In [141]:
query = """
SELECT
    item_purchased,
    round(AVG(review_rating),2) AS avg_rating
FROM mytable
GROUP BY item_purchased
ORDER BY avg_rating DESC
LIMIT 5;
"""
result = pd.read_sql_query(query, conn)
result

  item_purchased  avg_rating
0         Gloves        3.86
1        Sandals        3.84
2          Boots        3.82
3            Hat        3.80
4        T-shirt        3.78

In [142]:
query = """
SELECT
    shipping_type,
    round(AVG(purchase_amount),2) AS avg_purchase
FROM mytable
WHERE shipping_type IN ('Express','Standard')
GROUP BY shipping_type;
"""
result = pd.read_sql_query(query, conn)
result

  shipping_type  avg_purchase
0       Express         60.48
1      Standard         58.46

In [143]:
query = """
SELECT
    subscription_status,
    round(AVG(purchase_amount),2) AS avg_spend,
    SUM(purchase_amount) AS total_revenue
FROM mytable
GROUP BY subscription_status;
"""
result = pd.read_sql_query(query, conn)
result

  subscription_status  avg_spend  total_revenue
0                  No      59.87         170436
1                 Yes      59.49          62645

In [144]:
query = """
SELECT
    item_purchased,
    ROUND(COUNT(CASE WHEN discount_applied = 'Yes' THEN 1 END) * 100.0 / COUNT(*),2) AS discount_percentage
FROM mytable
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;
"""
result = pd.read_sql_query(query, conn)
result

  item_purchased  discount_percentage
0            Hat                50.00
1       Sneakers                49.66
2           Coat                49.07
3        Sweater                48.17
4          Pants                47.37

In [145]:
query = """
SELECT
    CASE
        WHEN previous_purchases = 0 THEN 'New'
        WHEN previous_purchases BETWEEN 1 AND 5 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment,
    COUNT(*) AS count
FROM mytable
GROUP BY customer_segment;
"""
result = pd.read_sql_query(query, conn)
result

  customer_segment  count
0            Loyal   3476
1        Returning    424

In [146]:
query = """
SELECT *
FROM (
    SELECT
        category,
        item_purchased,
        COUNT(*) AS purchase_count,
        ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(*) DESC) AS rank
    FROM mytable
    GROUP BY category, item_purchased
)
WHERE rank <= 3;
"""
result = pd.read_sql_query(query, conn)
result

       category item_purchased  purchase_count  rank
0   Accessories        Jewelry             171     1
1   Accessories     Sunglasses             161     2
2   Accessories           Belt             161     3
3      Clothing          Pants             171     1
4      Clothing         Blouse             171     2
5      Clothing          Shirt             169     3
6      Footwear        Sandals             160     1
7      Footwear          Shoes             150     2
8      Footwear       Sneakers             145     3
9     Outerwear         Jacket             163     1
10    Outerwear           Coat             161     2

In [147]:
query = """
SELECT
    subscription_status,
    COUNT(*) AS count
FROM mytable
WHERE previous_purchases > 5
GROUP BY subscription_status;
"""
result = pd.read_sql_query(query, conn)
result

  subscription_status  count
0                  No   2518
1                 Yes    958

In [148]:
query = """
SELECT
     age_group,
    SUM(purchase_amount) AS total_revenue
FROM mytable
GROUP BY age_group
order by total_revenue desc;
"""
result = pd.read_sql_query(query, conn)
result

      age_group  total_revenue
0  Young Adults          62143
1   Middle Aged          59197
2         Adult          55978
3        Senior          55763

In [149]:
query = """
SELECT
    category,
    AVG(review_rating) AS avg_rating
FROM mytable
GROUP BY category;
"""
result = pd.read_sql_query(query, conn)
result

      category  avg_rating
0  Accessories    3.770242
1     Clothing    3.721301
2     Footwear    3.793823
3    Outerwear    3.745988

In [150]:
query = """
SELECT
    category,
    SUM(purchase_amount) AS revenue
FROM mytable
GROUP BY category
ORDER BY revenue DESC
LIMIT 1;
"""
result = pd.read_sql_query(query, conn)
result

   category  revenue
0  Clothing   104264

In [151]:
query = """
SELECT
    customer_id,
    SUM(purchase_amount) AS total_spent,
    RANK() OVER (ORDER BY SUM(purchase_amount) DESC) AS rank
FROM mytable
GROUP BY customer_id;
"""
result = pd.read_sql_query(query, conn)
result

      customer_id  total_spent  rank
0            3838          100     1
1            3726          100     1
2            3322          100     1
3            3266          100     1
4            3029          100     1
...           ...          ...   ...
3895          295           20  3849
3896          256           20  3849
3897           53           20  3849
3898           27           20  3849
3899            6           20  3849

[3900 rows x 3 columns]

In [152]:
df.to_csv('my_data.csv', index=False)

In [156]:
from google.colab import files
files.download("my_data.csv")